2018-05-19 12:57:53,548 ERROR: Exception on / [GET] [in /Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/templates/base.html", line 34, in template
    {% block app-app_content %}
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/templates/base.html", line 34, in template
    {% block app-app_content %}
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 264, in parse_block
    self.fail('Block names in Jinja have to be valid Python '
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Block names in Jinja have to be valid Python identifiers and may not contain hyphens, use an underscore instead.
2018-05-19 12:58:34,951 INFO: Microblog startup [in /Users/KLM/Desktop/Programming/Webdev/microblog/app/__init__.py:42]
2018-05-19 12:58:38,198 ERROR: Exception on / [GET] [in /Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends "boostrap/base.html" %}
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/KLM/Desktop/Programming/Webdev/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: boostrap/base.html
